services:
    web:
      container_name: web
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 8000:8000
      networks:
        - web-net
      depends_on:
        - db

    db:
      container_name: postgres-db
      image: postgres
      ports:
        - target: 5432
          protocol: tcp
          mode: bridge
      environment:
        POSTGRES_HOST_AUTH_METHOD: trust
        PGDATA: /data/postgres
      volumes:
        - postgres-vol:/data/postgres
      networks:
        - web-net
      restart: unless-stopped

networks:
  web-net:
    driver: bridge

volumes:
  postgres-vol: